### ISSUE TITLE
8 GB wiiu 

### ISSUE THREAD

**Issue by opendata26** [opendata26/Nand-Manager#2]
Need to implement compatibility with 8gb wiiu.

**Comment by Saladien** [comment]
Is there any way to help with this? Im waiting eagerly :) Great job so far.

**Comment by opendata26** [comment]
I need to redo the gui as it broke in a recent gtk update then i will add this

**Comment by opendata26** [comment]
Issue will be fixed in next commit, i have made it commandline only for now
