### ISSUE TITLE
(archlinux) Window does not respond?

### ISSUE THREAD

**Issue by mariogamer2** [opendata26/Nand-Manager#6]
After running sudo ./nand_manager /dev/mmcblk0 /dev/mmcblk0, then after choosing dest.,it seem like it doesn't do nothing when clicking on read...

**Comment by opendata26** [comment]
Does the text box in the middle change

**Comment by opendata26** [comment]
Also make sure sure you are running it with sudo you might need to disable selinux

**Comment by mariogamer2** [comment]
The text is somewhat under the Write button.

I used sud´,but what is selinux?

**Comment by opendata26** [comment]
Selinux is a module that can stop you from writing orv readinv ciertan files 
EDIT: Think something broke with the latest gtk in arch
Can you send a picture of the program after clicking read

**Comment by opendata26** [comment]
Issue will be fixed in next commit

**Comment by mariogamer2** [comment]
Ok thank.
